const express=require('express')
const userRouter=require("./userRouter.js") 
const adminRouter=require("./adminRouter.js")
const cartRouter=require("./cartRouter.js")
const couponRouter=require("./couponRouter.js")
const dishRouter=require("./dishRouter.js")
const orderRouter=require("./orderRouter.js")
const ownerRouter=require("./ownerRouter.js")
const restaurantRouter=require("./restaurantRouter.js")
const reviewRouter=require("./reviewRouter.js")
const paymentRouter=require("./paymentRouter.js")
const searchRouter=require("./searchRouter.js")
const router =express.Router()

router.use('/user',userRouter)
router.use('/admin',adminRouter)
router.use('/cart',cartRouter)
router.use('/coupon',couponRouter)
router.use('/dish',dishRouter)
router.use('/order',orderRouter)
router.use('/owner',ownerRouter)
router.use("/restaurant",restaurantRouter)
router.use("/review",reviewRouter)
router.use('/payment',paymentRouter)
router.use('/search',searchRouter)
router.use('/payment',paymentRouter)
//  module.exports.apiRouter=router
module.exports=router
